### ISSUE TITLE
It's TicTacToe.c not tictactoe.c

### ISSUE THREAD

**Issue by ilorez** [AKL001/TicTacToe-in-C#1]
https://github.com/AKL001/TicTacToe-in-C/blob/e2c15424e2c76057ca965cfac9fa81527fdd9aa5/README.md?plain=1#L23

**Comment by ilorez** [comment]
good job keep going 🔥

**Comment by AKL001** [comment]
Great catch on that issue! 👍 Thanks, brother! 🙏
